### ISSUE TITLE
Lazy addin loading checklist

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4399]
As of https://github.com/mono/monodevelop/pull/4398, we now have some logging of why addins are getting loaded.

* [ ] PlatformService force loads addins which define mimetype nodes 

Solutions:
1. Don't define mimetype extension nodes scattered in all the addins?
2. Don't force load children? It was introduced in this commit: https://github.com/mono/monodevelop/commit/7d3715d03df93712aa60af189049bb69ee2c8ecc

* [ ] FileService static constructor loads file system extension nodes

Solutions:
1. Route the internal extension node implementation to another static embedded class. That way, subscribing to the event handlers does not force initialization of the extension objects

* [ ] Command nodes seem to be loading addins?

Solutions:
?

> VS bug [#593847](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593847)

**Comment by Therzok** [comment]
These have been split across multiple user stories in VSTS. Will close.
